AbilityConstants = {
  MINOR_WALL_BOUNCES: 2,
  MAJOR_WALL_BOUNCES: 3,

  BOUNCE_DAMAGE_PENALTY: 0.8,
  PASSTHROUGH_DAMAGE_PENALTY: 0.75,
  MULTISHOT_DAMAGE_PENALTY: 0.65,
  MULTISHOT_RADIUS_PENALTY: 0.8,
}
